### ISSUE TITLE
匿名用户访问问题

### ISSUE THREAD

**Issue by jiang-taibai** [jiang-taibai/deploy-outline-via-nginx#2]
该问题由某网友提出，详细问题描述：
Outline 私有化部署之后, 现在可以支持 匿名用户 的访问吗?

**Comment by jiang-taibai** [comment]
由于不清楚您说的“访问”具体指什么，这里分点回答：
## 1. 是否支持“匿名用户”作为编辑者？

主要看“OIDC”服务是否支持，本文档使用的是“KeyCloak”，支持用户自行注册（但文档中没有写）。

但匿名访问去作为编辑者本身是不太安全的行为，所以 Outline 也可以支持设置新注册用户的角色。

![图片](https://github.com/jiang-taibai/deploy-outline-via-nginx/assets/66373624/f14443e8-df51-4246-a1aa-93fc72b4564a)

其次 Outline 也可以继续修改角色的权限层级。

![图片](https://github.com/jiang-taibai/deploy-outline-via-nginx/assets/66373624/fcfa38bc-91e2-4fd2-92ee-d7d665843ff2)

## 2. 是否支持“匿名用户”作为浏览者查看您分享的文档？

完全可以，当您分享文档到互联网后，其他人无需注册，就可以看到您分享的文章（也包括文章内的图片、视频、附件等等）

**Comment by yanguangshaonian** [comment]
感谢回答,  已经解答了我的需求

**Comment by yanguangshaonian** [comment]
> 由于不清楚您说的“访问”具体指什么，这里分点回答：
> 
> ## 1. 是否支持“匿名用户”作为编辑者？
> 主要看“OIDC”服务是否支持，本文档使用的是“KeyCloak”，支持用户自行注册（但文档中没有写）。
> 
> 但匿名访问去作为编辑者本身是不太安全的行为，所以 Outline 也可以支持设置新注册用户的角色。
> 
> ![图片](https://private-user-images.githubusercontent.com/66373624/286892778-f14443e8-df51-4246-a1aa-93fc72b4564a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMzk1OTEsIm5iZiI6MTcwMTMzOTI5MSwicGF0aCI6Ii82NjM3MzYyNC8yODY4OTI3NzgtZjE0NDQzZTgtZGY1MS00MjQ2LWExYWEtOTNmYzcyYjQ1NjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDEwMTQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExZTZkNTM5MGZhMzU0MTVkMjc2ZTA4ZGNhNmI2NmQyOWRhNmY4N2Y5NjUyMDBiYWNmZmNjNDAyMjVlMTlhMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wJCE2_wzjoGu404oftk6rMB1Pj215VNBrt4l_U_vyn8)
> 
> 其次 Outline 也可以继续修改角色的权限层级。
> 
> ![图片](https://private-user-images.githubusercontent.com/66373624/286892817-fcfa38bc-91e2-4fd2-92ee-d7d665843ff2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMzk1OTEsIm5iZiI6MTcwMTMzOTI5MSwicGF0aCI6Ii82NjM3MzYyNC8yODY4OTI4MTctZmNmYTM4YmMtOTFlMi00ZmQyLTkyZWUtZDdkNjY1ODQzZmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDEwMTQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMmQ4OTEzYzJiNGZiNDMyZGI2OTRhMzU1MWZiY2U5YjBhNjU3YjFiNTI4Yjg2MDQ3MmQzODZhOGUxNmY2YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z0r6i-AEBl6dxy-AmROKRIatZDE6xWrotDZY4qzzfaE)
> 
> ## 2. 是否支持“匿名用户”作为浏览者查看您分享的文档？
> 完全可以，当您分享文档到互联网后，其他人无需注册，就可以看到您分享的文章（也包括文章内的图片、视频、附件等等）

感谢回答
