### ISSUE TITLE
内网配置教程

### ISSUE THREAD

**Issue by YangWang0514** [jiang-taibai/deploy-outline-via-nginx#5]
按照您这边给的方法，在内网配置有一些问题，比如不需要 ssl 证书，用你写的文档部署会报错

**Comment by jiang-taibai** [comment]
请问具体报错是什么？哪一步出现了问题？

**Comment by YangWang0514** [comment]
https://blog.csdn.net/Duke147/article/details/128136056
还在拉镜像的时候就出现了这个报错，按照这个方法解决了

**Comment by YangWang0514** [comment]
方便微信联系么

**Comment by jiang-taibai** [comment]
了解到是什么错误了，我在原文中忘记添加这一部分的操作了，谢谢您的反馈，我有时间把这部分完善一下。
后续有问题的话欢迎随时在 issue 提出，我会根据大家的 issue 有序地完善文档
